### ISSUE TITLE
JobScheduler makes the app crash randomly in Android 5 and 6

### ISSUE THREAD

**Issue by JefersonR** [ibm-mobile-push/android#10]
I am having many reports of this problem after adding the library on android 5 and 6.

`Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.android.server.job.controllers.JobStatus.getUid()' on a null object reference
       at android.os.Parcel.readException(Parcel.java:1552)
       at android.os.Parcel.readException(Parcel.java:1499)
       at android.app.job.IJobCallback$Stub$Proxy.jobFinished(IJobCallback.java:167)
       at android.app.job.JobService$JobHandler.handleMessage(JobService.java:147)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6934)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)`

**Comment by anatideo** [comment]
I am getting the same issue!

**Comment by andrewcib** [comment]
Should be fixed in Android 3.7.1.3.1.
