### ISSUE TITLE
NullPointerException in NotifActionReceiver.onReceive

### ISSUE THREAD

**Issue by carhag** [ibm-mobile-push/android#11]
```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Set android.os.BaseBundle.keySet()' on a null object reference
       at com.ibm.mce.sdk.notification.NotifActionReceiver.onReceive(NotifActionReceiver.java:50)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3252)
       at android.app.ActivityThread.-wrap17(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1677)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6541)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

SDK version: 3.7.1.2.12

**Comment by andrewcib** [comment]
Fixed in Android SDK 3.7.1.3.1
