### ISSUE TITLE
Inconsistencies between documentation and sample app, NoClassDefFoundError

### ISSUE THREAD

**Issue by l-barbosa** [ibm-mobile-push/android#7]
Hi,

I've found inconsistencies between the documentation and the sample app, one of them possibly leading to an error that's preventing the SDK from working.
Here's the documentation I'm referring to:
https://developer.ibm.com/customer-engagement/tutorials/getting-started-mobile-app-messaging-android-apps/

The documentation tells us to add the following dependencies:

```
compile fileTree(dir: 'libs', include: ['*.jar'])
 compile 'com.android.support:appcompat-v7:21.+'
 compile 'com.google.android.gms:play-services-base:<play-services version>'
 compile 'com.google.firebase:firebase-messaging:<play-services version>'
If you use location:
compile 'com.google.android.gms:play-services-location:<play-services version>'
```

However, the sample app uses:

```
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:26.+'
    compile 'com.google.android.gms:play-services-gcm:10.2.1'
    compile 'com.google.android.gms:play-services-base:10.2.1'
    compile 'com.google.android.gms:play-services-location:10.2.1'
    compile 'com.google.android.gms:play-services-maps:10.2.1'
```

Notice the inclusion of "firebase-messaging" in one case and "gcm" in the other.
When I saw this, I thought that maybe the sample app is still using GCM, which would be fine, but on the manifest, we find:

```
        <!-- FCM Registration -->
        <service
            android:name="com.ibm.mce.sdk.fcm.FcmInstanceIdService">
            <intent-filter>
                <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
            </intent-filter>
        </service>

        <!-- FCM Messages -->
        <service
            android:name="com.ibm.mce.sdk.fcm.FcmMessagingService">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT"/>
            </intent-filter>
        </service>
```

Which seems to confirm that the sample app is trying to use FCM. Another inconsistency here, for FCM implementation, is that the documentation is not mentioning the intent-filters, just:

```
<service android:name=“com.ibm.mce.sdk.fcm.FcmInstanceIdService” />
<service android:name=“com.ibm.mce.sdk.fcm.FcmMessagingService” />
```

Now, the real issue here is that when following the documentation, after launching the app, we see in the logs:

```
E/IBM.MCE 3.7.1.2.4 : GCM: Failed to register gcm
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/gcm/GoogleCloudMessaging;
        at com.ibm.mce.sdk.gcm.Gcm.register(Unknown Source)
        at com.ibm.mce.sdk.gcm.GcmDeliveryChannel.register(Unknown Source)
        at com.ibm.mce.sdk.registration.DeliveryChannel.register(Unknown Source)
        at com.ibm.mce.sdk.registration.RegistrationIntentService.onQueueTrigger(Unknown Source)
        at com.ibm.mce.sdk.wi.QueueAlarmListener.onWakefulTrigger(Unknown Source)
        at com.ibm.mce.sdk.wi.WakefulAlarmListener.doWakefulWork(Unknown Source)
        at com.ibm.mce.sdk.wi.WakefulIntentService.onHandleIntent(Unknown Source)
        at com.ibm.mce.sdk.wi.QueueAlarmListener.callFromJob(Unknown Source)
        at com.ibm.mce.sdk.wi.QueueJob.startJob(Unknown Source)
        at com.ibm.mce.sdk.job.MceJobService$1.run(Unknown Source)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.gcm.GoogleCloudMessaging" on path: DexPathList[[zip file....
```

Which makes sense because we're not including the GCM dependency, just FCM.

Finally, one more issue we've seen logged is:

```
Key com.ibm.mce.WakefulIntentService expected String but value was a android.os.Bundle.  The default value <null> was returned.
    Attempt to cast generated internal exception:
    java.lang.ClassCastException: android.os.Bundle cannot be cast to java.lang.String
        at android.os.BaseBundle.getString(BaseBundle.java:995)
        at com.ibm.mce.sdk.wi.QueueAlarmListener.callFromJob(Unknown Source)
        at com.ibm.mce.sdk.wi.QueueJob.startJob(Unknown Source)
        at com.ibm.mce.sdk.job.MceJobService$1.run(Unknown Source)
```

For context, this is an implementation that was working as expected with GCM and was now migrated to FCM, by following the instructions in the documentation.

Thanks

**Comment by l-barbosa** [comment]
Just a quick update, I've just reverted the migration from GCM to FCM but still updated the SDK to the latest version (something I forgot to mention in the ticket above that was done simultaneously with the migration) and I'm still getting that last message being logged:

```
Key com.ibm.mce.WakefulIntentService expected String but value was a android.os.Bundle.  The default value <null> was returned.
    Attempt to cast generated internal exception:
    java.lang.ClassCastException: android.os.Bundle cannot be cast to java.lang.String
        at android.os.BaseBundle.getString(BaseBundle.java:995)
        at com.ibm.mce.sdk.wi.QueueAlarmListener.callFromJob(Unknown Source)
        at com.ibm.mce.sdk.wi.QueueJob.startJob(Unknown Source)
        at com.ibm.mce.sdk.job.MceJobService$1.run(Unknown Source)
```
